version: '3'
services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5452:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres1
      - POSTGRES_DB=auth_server
    volumes:
      - ./log-directory:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  authServer:
    image: 'franff96/auth_server:latest'
    container_name: authServer
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./:/opt/app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=auth_server
      - ENV_PORT=8081
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres1