login:
  custom-login: ${CUSTOM_LOGIN}
  application-domain: ${APP_DOMAIN}
  redirect-url: ${REDIRECT_URL}
  enable-redirect: ${ENABLE_REDIRECT}
spring:
  devtools:
    add-properties: false
  mustache:
    check-template-location: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - user
              - read:user
              - user:email
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: oauth
server:
  port: ${ENV_PORT}
vaadin:
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.component.authserver
logging:
  level:
    com.component.authserver: DEBUG
#    org.springframework.security: TRACE